#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mobile-broadband-provider-info
Version  : 20170310
Release  : 1
URL      : https://github.com/GNOME/mobile-broadband-provider-info/archive/20170310.tar.gz
Source0  : https://github.com/GNOME/mobile-broadband-provider-info/archive/20170310.tar.gz
Summary  : Mobile Broadband Service Provider Information Database
Group    : Development/Tools
License  : PublicDomain
Requires: mobile-broadband-provider-info-data
BuildRequires : libxml2-dev

%description
This package contains mobile broadband settings for different service providers
in different countries. The Package contains only informational files so it's
safe for distributions to grab updates even during feature freeze and
maintenance stages.

%package data
Summary: data components for the mobile-broadband-provider-info package.
Group: Data

%description data
data components for the mobile-broadband-provider-info package.


%package dev
Summary: dev components for the mobile-broadband-provider-info package.
Group: Development
Requires: mobile-broadband-provider-info-data
Provides: mobile-broadband-provider-info-devel

%description dev
dev components for the mobile-broadband-provider-info package.


%prep
%setup -q -n mobile-broadband-provider-info-20170310

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530114341
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1530114341
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/mobile-broadband-provider-info/serviceproviders.2.dtd
/usr/share/mobile-broadband-provider-info/serviceproviders.xml

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/mobile-broadband-provider-info.pc
